version: '3.9'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  flyway-core:
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:mysql://db -schemas=mvc -user=root -password=root -connectRetries=50 migrate
    volumes:
      - ./migration:/flyway/sql
    depends_on:
      - db
